baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
disableKinds = ['taxonomy', 'taxonomyTerm']
[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "extra-content"
target = "content/resources"

[[module.mounts]]
source = "extra-content"
target = "content/more-resources"
